name:                DerpHs
version:             0.1.0.0
github:              "githubuser/DerpHs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DerpHs#readme>

dependencies:
- base              >= 4.7 && < 5
- bytestring        >= 0.10.8.2
- mysql-simple      >= 0.4.5
- postgresql-simple >= 0.5.4.0
- HTTP              >= 4000.3.11
- dates             >= 0.2.2.1
- time              >= 1.8.0.2
- aeson             >= 1.4.0.0
- text              >= 1.2.2.2
- http-conduit      >= 2.0.0.3
- attoparsec        >= 0.13.2.2
- uri-encode        >= 1.5.0.5
- yaml              >= 0.8.30
- text-show         >= 3.7.2

library:
  source-dirs: src

executables:
  DerpHs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DerpHs

tests:
  DerpHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DerpHs
